DROP TABLE IF EXISTS `shihun_config`;</explode>
CREATE TABLE `shihun_config` (
  `id` int(1) NOT NULL AUTO_INCREMENT,
  `switch` int(1) NOT NULL DEFAULT '1',
  `user` varchar(250) NOT NULL,
  `pwd` varchar(250) NOT NULL,
  `sitename` varchar(50) NOT NULL,
  `keywords` text NOT NULL,
  `description` text NOT NULL,
  `dh1` text NOT NULL,
  `dh2` text NOT NULL,
  `dh3` text NOT NULL,
  `dh4` text NOT NULL,
  `dh5` text NOT NULL,
  `dh5dz` text NOT NULL,
  `server` text NOT NULL,
  `spjianjie` text NOT NULL,
  `xcp` text NOT NULL,
  `xcptu` text NOT NULL,
  `tesetu1` text NOT NULL,
  `tesetu2` text NOT NULL,
  `tesetu3` text NOT NULL,
  `tese1` text NOT NULL,
  `tese2` text NOT NULL,
  `tese3` text NOT NULL,
  `tesejianjie1` text NOT NULL,
  `tesejianjie2` text NOT NULL,
  `tesejianjie3` text NOT NULL,
  `tuanduitu1` text NOT NULL,
  `tuanduitu2` text NOT NULL,
  `tuanduitu3` text NOT NULL,
  `tuandui1` text NOT NULL,
  `tuandui2` text NOT NULL,
  `tuandui3` text NOT NULL,
  `tuanduijianjie1` text NOT NULL,
  `tuanduijianjie2` text NOT NULL,
  `tuanduijianjie3` text NOT NULL,
  `tp1` text NOT NULL,
  `tp2` text NOT NULL,
  `tp3` text NOT NULL,
  `tp4` text NOT NULL,
  `tp5` text NOT NULL,
  `tp6` text NOT NULL,
  `khd` text NOT NULL,
  `jianjie` text NOT NULL,
  `jq` text NOT NULL,
  `music` varchar(250) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;</explode>
INSERT INTO `shihun_config`(`id`, `switch`, `user`, `pwd`, `sitename`, `keywords`, `description`, `dh1`, `dh2`, `dh3`, `dh4`, `dh5`, `dh5dz`, `server`,  `khd`, `jianjie`, `jq`, `music`) VALUES
('1', '1', 'admin', '123456', 'Minecraft - XX服务器', '我的世界', '打造完美服务器',  '主页', '服务器宣传片',  '服务器特色',   '',   '',  '',  'XX服务器',  'http://',  '服务器简介',  'http://', 'http://');</explode>